Add check on client-side to see if KnitServer exists before destroying it
AtollStudios/Knit pull request #117
Opened 2021-07-05 12:40 UTC by aku-e

I was testing a module that uses utility modules from Knit using the command bar on the client-side when Knit threw an error saying "KnitServer" does not exist.

I realized this was because the Knit module had already been required by client-side scripts, thus had deleted the KnitServer module, but since the command bar runs in a separate scope/context (not sure of the correct terminology here) it requires it again, then tries to find an instance that is no longer under the Knit module and errors.

This would allow for modules to be tested via the command bar during the run-time on the client-side.

2021-07-08 14:12 UTC, Sleitnick commented
I wonder if there is a better way to go about testing modules than through the command line? I don't have any issues with this change, but it does highlight a possible need for a tool or something to help test

2021-07-08 14:13 UTC, Sleitnick requested changes

2021-07-08 14:13 UTC, Sleitnick commented on src/init.lua
> +	if KnitServer then
To conform to our styles, can you wrap this in parenths? e.g. `if (KnitServer) then`

2021-07-09 10:49 UTC, aku-e commented on src/init.lua
> +	if KnitServer then
Done 🙂

2021-07-09 10:51 UTC, aku-e commented
I sometimes test code from the command bar as sometimes it's more convenient than writing some temporary code in some file somewhere, just to make sure a module works properly before starting work on a gameplay feature.

2021-07-09 11:29 UTC, aku-e commented
> I sometimes test code from the command bar as sometimes it's more convenient than writing some temporary code in some file somewhere, just to make sure a module works properly before starting work on a gameplay feature.

Oops, forgot to mention: yes, there probably is a better way of going about testing modules.

2021-07-13 17:48 UTC, aku-e commented
My bad didn't know that I need to re-request a review once I've implemented the changes the review wants. I'm still pretty new to GitHub pull request stuff😅

2021-08-25 13:20 UTC, Sleitnick approved these changes

2021-08-25 13:21 UTC, merged